import { defineConfig } from 'vite';
import pluginCombine from 'vite-plugin-combine';

/**
 * 示例 5：beforeWrite 钩子 — 写入前修改合并代码
 *
 * beforeWrite 接受 (code: string) => string 函数，
 * 在合并代码写入磁盘前做最后处理（如追加 re-export、banner 等）。
 */
export default defineConfig({
  plugins: [
    pluginCombine({
      src: ['src/util/*.ts', '!src/util/typings.ts'],
      target: 'src/combine.5.ts',
      nameExport: true,
      //   logLevel: 'TRACE',
      beforeWrite(code) {
        /*
         * beforeWrite：在组合代码写入临时入口文件前做最后改写。
         * 这里做两件事配合测试验证（config 5 的标题就是"prepends banner comment"）：
         *   1. 用 /*! ... * / 块注释 banner（带 ! 前缀，Rolldown output.comments 默认不会清掉 license/banner 类块注释）
         *   2. 把 `Auto-generated by vite-plugin-combine` 这个标识字符串写进 banner，
         *      配合 build.rolldownOptions.output.comments: 'preserve-legal'
         *      或 true 时最终 dist 产物也能看到 banner。
         */
        return `/*! Auto-generated by vite-plugin-combine - beforeWrite banner */\n${code}`;
      },
      dts: true
    })
  ],
  build: {
    outDir: 'dist/5',
    minify: false,
    rolldownOptions: {
      output: {
        // Rolldown comments accepts boolean | BindingCommentsOptions (NOT a
        // string like rollup's 'preserve-legal'). Setting `comments: true`
        // keeps all comments in the ES output, including the /*! banner */
        // we prepend via beforeWrite. This must be enabled so the test can
        // assert "banner comment was prepended" against the final dist file.
        comments: true
      }
    },
    lib: {
      entry: [],
      formats: ['es'],
      fileName: '[name]'
    }
  }
});
