import { execSync } from 'node:child_process';
import { existsSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

const root = join(__dirname, '..');

function build(n: number) {
  execSync(`pnpm run build:${n}`, { cwd: root, stdio: 'pipe' });
}

function read(...segments: string[]) {
  return readFileSync(join(root, ...segments), 'utf-8');
}

afterEach(() => {
  const p = join(root, 'dist');
  if (existsSync(p)) {
    rmSync(p, { recursive: true, force: true });
  }
});

describe('vite-plugin-combine example configs', () => {
  it('config 1: nameExport — camelCase named exports', () => {
    build(1);
    const code = read('dist/1/combine.1.js');
    // nameExport: true → named exports like `export { isNil, isDate, ... }`.
    expect(code).toContain('export');
    // Should re-export individual util modules.
    expect(code).toMatch(/isAsyncFunction|isDate|isError|isNil|isNumber|noop/);
  }, 60000);

  it('config 2: exports "default" — default export object', () => {
    build(2);
    const code = read('dist/2/combine.2.js');
    // exports: 'default' → `export { ... as default }`.
    expect(code).toContain('as default');
  }, 60000);

  it('config 3: exports "both" — named + default', () => {
    build(3);
    const code = read('dist/3/combine.3.js');
    // exports: 'both' → named exports + `as default`.
    expect(code).toContain('as default');
    expect(code).toMatch(/export \{.*isAsyncFunction/);
  }, 60000);

  it('config 4: nameExport function — custom prefix', () => {
    build(4);
    const code = read('dist/4/combine.4.js');
    // nameExport(name) => `my${Name}` → exports prefixed with "my".
    expect(code).toMatch(/myIs/);
  }, 60000);

  it('config 5: beforeWrite — prepends banner comment', () => {
    build(5);
    const code = read('dist/5/combine.5.js');
    // beforeWrite prepends a banner comment (/* !... */ block comment with
    // "Auto-generated by vite-plugin-combine") to the combined source file
    // BEFORE it is written to disk. Rolldown is configured with
    // output.comments: 'preserve-legal' so the banner comment is preserved
    // all the way into the final dist output — if beforeWrite never ran
    // (or ran but failed to prepend), this marker string would be absent.
    expect(code).toContain('Auto-generated by vite-plugin-combine');
    // As a secondary sanity check: the output still imports/exports the
    // combined modules (this does NOT stand in for the banner assertion,
    // it just confirms the file was actually processed as a combined entry).
    expect(code).toContain('isAsyncFunction');
  }, 60000);

  it('config 6: exports "none" — side-effect imports only', () => {
    build(6);
    const code = read('dist/6/combine.6.js');
    // exports: 'none' → only side-effect imports, no named re-exports.
    expect(code).toMatch(/^import "\.\//);
    // Should NOT contain named re-exports.
    expect(code).not.toMatch(/export \{ is/);
  }, 60000);
});
