# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]

# jobs:
#   publish-combine:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           registry-url: https://registry.npmjs.org/
#       - run: npm publish ./packages/vite-plugin-combine
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  # publish-cp:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm publish ./packages/vite-plugin-cp
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  # publish-external:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm publish ./packages/vite-plugin-external
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  # publish-hook-use:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm publish ./packages/vite-plugin-hook-use
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  # publish-include-css:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm publish ./packages/vite-plugin-include-css
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  # publish-mock-data:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm publish ./packages/vite-plugin-mock-data
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  # publish-reverse-proxy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm publish ./packages/vite-plugin-reverse-proxy
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}
